### ISSUE TITLE
Update for React 16 (Fiber)

### ISSUE THREAD

**Issue by djfarly** [zilverline/react-tap-event-plugin#102]
Hey,
first of all thanks for the project. ;)

The current alpha of react 16 uses flat bundles (currently 16.0.0-alpha.13). Therefore there are no more react-dom/lib/* exports. There is a note in the [fiber umbrella issue](https://github.com/facebook/react/issues/8854) explicitly mentioning react-tap-event-plugin: 

> Maybe: Switch to flat bundles (no more react-dom/lib/*, internals are truly private)
> Decide: after flat bundles, how does one create a custom Fiber renderer?
> Decide: plan forward for popular projects depending on internals (react-native-web, react-tap-event-plugin)
> EventPluginHub is "dangerously" exported from flat bundle for tap event plugin

As far as i can see tap event plugin uses more exports from /lib than just EventPluginHub.
Namely:
- react-dom/lib/EventPluginHub
- react-dom/lib/EventConstants
- react-dom/lib/EventPluginUtils
- react-dom/lib/EventPropagators
- react-dom/lib/SyntheticUIEvent
- react-dom/lib/ViewportMetrics

React DOM currently exports:

<img width="551" alt="reactdomexports" src="https://user-images.githubusercontent.com/5230863/27287786-1afa54f8-5505-11e7-9632-c1732ffc4afb.png">

What would be the path forwards? 🙈 Is there some way to help?

For reference heres the output of the webpack build:
<details>

```
ERROR in ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-41
 @ dll vendor

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventConstants' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 22:21-60
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ dll vendor

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginUtils' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 23:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ dll vendor

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/EventPropagators' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 24:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ dll vendor

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/SyntheticUIEvent' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 25:23-64
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ dll vendor

ERROR in ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Can't resolve 'react-dom/lib/ViewportMetrics' in '[…]/node_modules/react-tap-event-plugin/src'
 @ ./node_modules/react-tap-event-plugin/src/TapEventPlugin.js 27:22-62
 @ ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js
 @ dll vendor
```

</details>

**Comment by spidergears** [comment]
Got this issue with `react-16.0.0-alpha.12`
`Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' in '[…]/node_modules/react-tap-event-plugin/src'`

What's the way fwd?

**Comment by KirillSuhodolov** [comment]
Have same issues with react 16.alpha

**Comment by cyrus-za** [comment]
Got the same issue with 15.6.1

works fine in dev but can't build. Using next.js

```javascript
"scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
}
```

**Comment by cyrus-za** [comment]
Seems like my issue is related to https://github.com/zilverline/react-tap-event-plugin/issues/99

**Comment by bsbechtel** [comment]
This issue has been open since June, but there isn't any recent activity on it. Has anyone proposed a path forward or come up with an alternative solution now that React 16 has been released? Thanks

**Comment by s0meone** [comment]
I've updated the plugin to version 3.0.0, to be compatible with React 16. I had to copy a big chunk of React internals to keep it working. This solution will probably not last for future versions. React is making it harder and harder to keep this plugin going.

Please test the latest commit in your application and let me know the results so I can publish to npm.

**Comment by maierson** [comment]
> This solution will probably not last for future versions.

`react-fastclick` works for us as a replacement.

```
// index.jsx
import * as initFastClick from "react-fastclick";
initFastClick();
```

**Comment by GuillaumeCisco** [comment]
Works great @s0meone , thanks ;)

**Comment by bsbechtel** [comment]
@s0meone I'm still seeing an error regarding the EventPluginHub: 
![screen shot 2017-09-28 at 9 29 29 am](https://user-images.githubusercontent.com/1334933/30969179-9e0de728-a42f-11e7-8555-4cfdd89f24d9.png)

**Comment by chenop** [comment]
Hi,
Thanks for maintaining this!
Any update regarding a new version that support React 16?
